@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"control.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	classify
	.thumb_func
	.type	 classify,function
classify:
	push	{lr}
	sub	r0, r0, #2
	cmp	r0, #4
	bhi	.L9
	ldr	r2, .L11
	lsl	r3, r0, #2
	ldr	r3, [r3, r2]
	mov	pc, r3
	.align	2, 0
	.align	2, 0
.L10:
	.word	.L4
	.word	.L5
	.word	.L6
	.word	.L7
	.word	.L8
.L4:
	mov	r0, #11
	b	.L2
.L5:
	mov	r0, #19
	b	.L2
.L6:
	mov	r0, #7
	b	.L2
.L7:
	mov	r0, #23
	b	.L2
.L8:
	mov	r0, #13
	b	.L2
.L9:
	mov	r0, #0
.L2:
	pop	{r1}
	bx	r1
.L12:
	.align	2, 0
.L11:
	.word	.L10
.Lfe1:
	.size	 classify,.Lfe1-classify
	.align	2, 0
	.global	accumulate
	.thumb_func
	.type	 accumulate,function
accumulate:
	push	{r5, lr}
	mov	r3, #1
	sub	r1, r1, #1
	neg	r3, r3
	mov	r4, r0
	mov	r0, #0
	cmp	r1, r3
	beq	.L20
	mov	r5, #1
	mov	ip, r3
.L16:
	ldrh	r2, [r4]
	mov	r3, r2
	and	r3, r3, r5
	add	r4, r4, #2
	cmp	r3, #0
	beq	.L17
	lsl	r3, r2, #3
	sub	r3, r3, r2
	add	r0, r0, r3
	b	.L14
.L17:
	lsl	r3, r2, #3
	eor	r0, r0, r3
.L14:
	sub	r1, r1, #1
	cmp	r1, ip
	bne	.L16
.L20:
	pop	{r5}
	pop	{r1}
	bx	r1
.Lfe2:
	.size	 accumulate,.Lfe2-accumulate
