@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"globals.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	update_state
	.thumb_func
	.type	 update_state,function
update_state:
	push	{r5, r6, lr}
	ldr	r4, .L3
	ldr	r3, .L3+4
	ldr	r5, [r4]
	ldr	r3, [r3]
	mov	r6, r0
	mov	r0, r5
	and	r3, r3, r1
	bic	r0, r0, r1
	orr	r0, r0, r3
	mov	r3, #15
	ldr	r2, .L3+8
	and	r3, r3, r6
	lsl	r3, r3, #2
	str	r0, [r2, r3]
	str	r0, [r4]
	bl	transform
	add	r0, r0, r5
	pop	{r5, r6}
	pop	{r1}
	bx	r1
.L4:
	.align	2, 0
.L3:
	.word	state_a
	.word	state_b
	.word	table
.Lfe1:
	.size	 update_state,.Lfe1-update_state
	.align	2, 0
	.global	repeated_address
	.thumb_func
	.type	 repeated_address,function
repeated_address:
	mov	r3, #15
	ldr	r2, .L6
	and	r3, r3, r0
	lsl	r3, r3, #2
	add	r3, r3, r2
	ldr	r2, .L6+4
	ldr	r1, [r3]
	ldr	r0, [r2]
	add	r0, r1, r0
	str	r0, [r3]
	eor	r0, r0, r1
	bx	lr
.L7:
	.align	2, 0
.L6:
	.word	table
	.word	state_b
.Lfe2:
	.size	 repeated_address,.Lfe2-repeated_address
