@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"padding.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	identity
	.thumb_func
	.type	 identity,function
identity:
	bx	lr
.Lfe1:
	.size	 identity,.Lfe1-identity
	.align	2, 0
	.global	multiply_seven
	.thumb_func
	.type	 multiply_seven,function
multiply_seven:
	mov	r3, r0
	lsl	r0, r3, #3
	sub	r0, r0, r3
	bx	lr
.Lfe2:
	.size	 multiply_seven,.Lfe2-multiply_seven
	.align	2, 0
	.global	mix_constant
	.thumb_func
	.type	 mix_constant,function
mix_constant:
	mov	r3, r0
	ldr	r0, .L5
	eor	r0, r0, r3
	bx	lr
.L6:
	.align	2, 0
.L5:
	.word	305419896
.Lfe3:
	.size	 mix_constant,.Lfe3-mix_constant
	.align	2, 0
	.global	narrow
	.thumb_func
	.type	 narrow,function
narrow:
	add	r0, r0, #3
	lsl	r0, r0, #16
	lsr	r0, r0, #16
	bx	lr
.Lfe4:
	.size	 narrow,.Lfe4-narrow
